# Generated by Django 5.2.3 on 2025-07-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        default="Aperature Booking",
                        help_text="Name of your lab or facility (displayed throughout the application)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one LabSettings instance can be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lab Settings",
                "verbose_name_plural": "Lab Settings",
                "db_table": "booking_labsettings",
            },
        ),
    ]
