# Generated by Django 4.2.11 on 2025-07-07 12:00

from django.db import migrations


def create_default_labsettings(apps, schema_editor):
    """Create default LabSettings if none exists."""
    LabSettings = apps.get_model('booking', 'LabSettings')
    if not LabSettings.objects.exists():
        LabSettings.objects.create(
            lab_name="Aperature Booking",
            is_active=True
        )


def reverse_func(apps, schema_editor):
    """No-op reverse function."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_labsettings'),
    ]

    operations = [
        migrations.RunPython(create_default_labsettings, reverse_func),
    ]