# Generated by Django 5.2.3 on 2025-07-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_ensure_labsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                help_text="Preferred theme (light, dark, or follow system)",
                max_length=10,
            ),
        ),
    ]
