# Generated by Django 4.2.23 on 2025-06-12 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0003_add_booking_templates"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookingtemplate",
            name="unique_user_template_name",
        ),
        migrations.AlterUniqueTogether(
            name="bookingtemplate",
            unique_together={("user", "name")},
        ),
    ]
