# Generated by Django 5.2.3 on 2025-07-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_add_google_calendar_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="lab_training_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Lab admin confirmed user completed lab training",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="lab_training_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="lab_training_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_lab_trainings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="lab_training_notes",
            field=models.TextField(
                blank=True, help_text="Notes about lab training completion"
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="safety_induction_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Lab admin confirmed user completed safety induction",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="safety_induction_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="safety_induction_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_safety_inductions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="safety_induction_notes",
            field=models.TextField(
                blank=True, help_text="Notes about safety induction completion"
            ),
        ),
    ]
