# Generated by Django 4.2.23 on 2025-06-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_add_notification_system"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="booking_not_user_id_c1f7ef_idx",
            old_name="booking_not_user_id_f8cea7_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="booking_not_notific_699f4b_idx",
            old_name="booking_not_notific_8b1e5e_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="booking_not_created_e8b12c_idx",
            old_name="booking_not_created_5c1b8f_idx",
        ),
    ]
