# Generated by Django 5.2.3 on 2025-07-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_add_access_request_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="supervisor_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of supervisor (required for students)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="supervisor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of supervisor (required for students)",
                max_length=200,
            ),
        ),
    ]
