# Generated by Django 5.2.3 on 2025-06-13 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_booking_not_user_id_f8cea7_idx_booking_not_user_id_c1f7ef_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('approval_request', 'Approval Request'), ('approval_decision', 'Approval Decision'), ('maintenance_alert', 'Maintenance Alert'), ('conflict_detected', 'Conflict Detected'), ('quota_warning', 'Quota Warning'), ('waitlist_joined', 'Joined Waiting List'), ('waitlist_availability', 'Waiting List Slot Available'), ('waitlist_cancelled', 'Left Waiting List')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('approval_request', 'Approval Request'), ('approval_decision', 'Approval Decision'), ('maintenance_alert', 'Maintenance Alert'), ('conflict_detected', 'Conflict Detected'), ('quota_warning', 'Quota Warning'), ('waitlist_joined', 'Joined Waiting List'), ('waitlist_availability', 'Waiting List Slot Available'), ('waitlist_cancelled', 'Left Waiting List')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('approval_request', 'Approval Request'), ('approval_decision', 'Approval Decision'), ('maintenance_alert', 'Maintenance Alert'), ('conflict_detected', 'Conflict Detected'), ('quota_warning', 'Quota Warning'), ('waitlist_joined', 'Joined Waiting List'), ('waitlist_availability', 'Waiting List Slot Available'), ('waitlist_cancelled', 'Left Waiting List')], max_length=30),
        ),
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_start_time', models.DateTimeField()),
                ('preferred_end_time', models.DateTimeField()),
                ('min_duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_duration_minutes', models.PositiveIntegerField(default=240)),
                ('flexible_start_time', models.BooleanField(default=True, help_text='Can start earlier/later than preferred time')),
                ('flexible_duration', models.BooleanField(default=True, help_text='Can accept shorter/longer slots')),
                ('max_days_advance', models.PositiveIntegerField(default=14, help_text='Maximum days in advance to consider')),
                ('notify_immediately', models.BooleanField(default=True)),
                ('notification_advance_hours', models.PositiveIntegerField(default=24, help_text='Hours notice before slot')),
                ('status', models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('auto_book', models.BooleanField(default=False, help_text='Automatically book when slot becomes available')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='booking.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_waitinglistentry',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_start_time', models.DateTimeField()),
                ('available_end_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('response_deadline', models.DateTimeField()),
                ('user_response', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Response Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking')),
                ('waiting_list_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.waitinglistentry')),
            ],
            options={
                'db_table': 'booking_waitinglistnotification',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['resource', 'status'], name='booking_wai_resourc_a500ad_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['user', 'status'], name='booking_wai_user_id_641ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['preferred_start_time'], name='booking_wai_preferr_71a92b_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['created_at'], name='booking_wai_created_eac388_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitinglistentry',
            unique_together={('resource', 'user', 'preferred_start_time')},
        ),
    ]
