# Generated by Django 5.2.3 on 2025-06-13 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_add_waiting_list_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, help_text='Actual usage end time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, help_text='Actual usage start time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_checked_out',
            field=models.BooleanField(default=False, help_text='System automatically checked out user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='When user actually checked in', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='When user actually checked out', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_show',
            field=models.BooleanField(default=False, help_text='User did not show up for booking'),
        ),
        migrations.CreateModel(
            name='CheckInOutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('no_show', 'No Show'), ('auto_check_out', 'Auto Check Out')], max_length=20)),
                ('timestamp', models.DateTimeField(help_text='When the event occurred')),
                ('actual_time', models.DateTimeField(blank=True, help_text='Actual start/end time if different from timestamp', null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_data', models.JSONField(blank=True, default=dict, help_text='GPS or location data if available')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_events', to='booking.booking')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_checkinoutevent',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['booking', 'event_type'], name='booking_che_booking_4dd74d_idx'), models.Index(fields=['timestamp'], name='booking_che_timesta_4e0618_idx'), models.Index(fields=['user', 'timestamp'], name='booking_che_user_id_5e0148_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('no_show_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('total_booked_minutes', models.PositiveIntegerField(default=0)),
                ('total_actual_minutes', models.PositiveIntegerField(default=0)),
                ('total_wasted_minutes', models.PositiveIntegerField(default=0)),
                ('utilization_rate', models.FloatField(default=0.0, help_text='Actual usage / Total available time')),
                ('efficiency_rate', models.FloatField(default=0.0, help_text='Actual usage / Booked time')),
                ('no_show_rate', models.FloatField(default=0.0, help_text='No shows / Total bookings')),
                ('avg_early_checkin_minutes', models.FloatField(default=0.0)),
                ('avg_late_checkin_minutes', models.FloatField(default=0.0)),
                ('avg_early_checkout_minutes', models.FloatField(default=0.0)),
                ('avg_late_checkout_minutes', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_analytics', to='booking.resource')),
            ],
            options={
                'db_table': 'booking_usageanalytics',
                'ordering': ['-date'],
                'unique_together': {('resource', 'date')},
            },
        ),
    ]
