# Generated by Django 5.2.3 on 2025-07-20 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_add_supervisor_fields_to_access_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="risk_assessment_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Lab admin confirmed user submitted required risk assessment",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="risk_assessment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="risk_assessment_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_risk_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="risk_assessment_notes",
            field=models.TextField(
                blank=True, help_text="Notes about risk assessment submission"
            ),
        ),
    ]
