# Generated by Django 4.2.23 on 2025-06-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_add_checkin_checkout_system"),
    ]

    operations = []
