# Generated by Django 4.2.23 on 2025-06-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_add_academic_hierarchy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "booking_college",
                "ordering": ["faculty__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Faculties",
                "db_table": "booking_faculty",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="staff_number",
            field=models.CharField(
                blank=True, help_text="Staff ID number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("undergraduate", "Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                ],
                help_text="Academic level (for students only)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="group",
            field=models.CharField(
                blank=True, help_text="Research group or class", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="student_id",
            field=models.CharField(
                blank=True, help_text="Student ID number", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="booking.college",
                    ),
                ),
            ],
            options={
                "db_table": "booking_department",
                "ordering": ["college__faculty__name", "college__name", "name"],
                "unique_together": {("college", "name"), ("college", "code")},
            },
        ),
        migrations.AddField(
            model_name="college",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colleges",
                to="booking.faculty",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.department",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.college",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="college",
            unique_together={("faculty", "code"), ("faculty", "name")},
        ),
    ]
