# Generated by Django 5.2.3 on 2025-06-13 21:50

from django.db import migrations


def rename_roles_forward(apps, schema_editor):
    """Rename role values from old names to new names."""
    UserProfile = apps.get_model('booking', 'UserProfile')
    
    # Update lab_manager to technician
    UserProfile.objects.filter(role='lab_manager').update(role='technician')
    
    # Update lecturer to academic
    UserProfile.objects.filter(role='lecturer').update(role='academic')


def rename_roles_reverse(apps, schema_editor):
    """Reverse the role renaming."""
    UserProfile = apps.get_model('booking', 'UserProfile')
    
    # Update technician back to lab_manager
    UserProfile.objects.filter(role='technician').update(role='lab_manager')
    
    # Update academic back to lecturer
    UserProfile.objects.filter(role='academic').update(role='lecturer')


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_add_userprofile_fields'),
    ]

    operations = [
        migrations.RunPython(rename_roles_forward, rename_roles_reverse),
    ]
