# Generated by Django 4.2.23 on 2025-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_rename_roles_lab_manager_to_technician_lecturer_to_academic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("researcher", "Researcher"),
                    ("academic", "Academic"),
                    ("technician", "Technician"),
                    ("sysadmin", "System Administrator"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
