# Generated by Django 5.2.3 on 2025-06-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_trainingrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="access_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.accessrequest",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="training_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.trainingrequest",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("booking_reminder", "Booking Reminder"),
                    ("approval_request", "Approval Request"),
                    ("approval_decision", "Approval Decision"),
                    ("maintenance_alert", "Maintenance Alert"),
                    ("conflict_detected", "Conflict Detected"),
                    ("quota_warning", "Quota Warning"),
                    ("waitlist_joined", "Joined Waiting List"),
                    ("waitlist_availability", "Waiting List Slot Available"),
                    ("waitlist_cancelled", "Left Waiting List"),
                    ("access_request_submitted", "Access Request Submitted"),
                    ("access_request_approved", "Access Request Approved"),
                    ("access_request_rejected", "Access Request Rejected"),
                    ("training_request_submitted", "Training Request Submitted"),
                    ("training_request_scheduled", "Training Scheduled"),
                    ("training_request_completed", "Training Completed"),
                    ("training_request_cancelled", "Training Cancelled"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("booking_reminder", "Booking Reminder"),
                    ("approval_request", "Approval Request"),
                    ("approval_decision", "Approval Decision"),
                    ("maintenance_alert", "Maintenance Alert"),
                    ("conflict_detected", "Conflict Detected"),
                    ("quota_warning", "Quota Warning"),
                    ("waitlist_joined", "Joined Waiting List"),
                    ("waitlist_availability", "Waiting List Slot Available"),
                    ("waitlist_cancelled", "Left Waiting List"),
                    ("access_request_submitted", "Access Request Submitted"),
                    ("access_request_approved", "Access Request Approved"),
                    ("access_request_rejected", "Access Request Rejected"),
                    ("training_request_submitted", "Training Request Submitted"),
                    ("training_request_scheduled", "Training Scheduled"),
                    ("training_request_completed", "Training Completed"),
                    ("training_request_cancelled", "Training Cancelled"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("booking_reminder", "Booking Reminder"),
                    ("approval_request", "Approval Request"),
                    ("approval_decision", "Approval Decision"),
                    ("maintenance_alert", "Maintenance Alert"),
                    ("conflict_detected", "Conflict Detected"),
                    ("quota_warning", "Quota Warning"),
                    ("waitlist_joined", "Joined Waiting List"),
                    ("waitlist_availability", "Waiting List Slot Available"),
                    ("waitlist_cancelled", "Left Waiting List"),
                    ("access_request_submitted", "Access Request Submitted"),
                    ("access_request_approved", "Access Request Approved"),
                    ("access_request_rejected", "Access Request Rejected"),
                    ("training_request_submitted", "Training Request Submitted"),
                    ("training_request_scheduled", "Training Scheduled"),
                    ("training_request_completed", "Training Completed"),
                    ("training_request_cancelled", "Training Cancelled"),
                ],
                max_length=30,
            ),
        ),
    ]
