# Generated by Django 5.2.3 on 2025-06-15 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_notification_access_request_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("in_app", "In-App"),
                    ("push", "Push Notification"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("in_app", "In-App"),
                    ("push", "Push Notification"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500)),
                (
                    "p256dh_key",
                    models.CharField(
                        help_text="Public key for encryption", max_length=100
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(help_text="Authentication secret", max_length=50),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Browser/device info", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_pushsubscription",
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
