# Generated by Django 5.2.3 on 2025-06-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_add_push_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFExportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration name", max_length=100, unique=True
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default configuration"
                    ),
                ),
                (
                    "default_quality",
                    models.CharField(
                        choices=[
                            ("high", "High Quality (2x scale)"),
                            ("medium", "Medium Quality (1.5x scale)"),
                            ("low", "Low Quality (1x scale)"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                (
                    "default_orientation",
                    models.CharField(
                        choices=[("landscape", "Landscape"), ("portrait", "Portrait")],
                        default="landscape",
                        max_length=10,
                    ),
                ),
                (
                    "include_header",
                    models.BooleanField(
                        default=True, help_text="Include enhanced header"
                    ),
                ),
                (
                    "include_footer",
                    models.BooleanField(
                        default=True, help_text="Include enhanced footer"
                    ),
                ),
                (
                    "include_legend",
                    models.BooleanField(
                        default=True, help_text="Include status legend"
                    ),
                ),
                (
                    "include_details",
                    models.BooleanField(
                        default=True, help_text="Include booking details in footer"
                    ),
                ),
                (
                    "preserve_colors",
                    models.BooleanField(
                        default=True, help_text="Maintain booking status colors"
                    ),
                ),
                (
                    "multi_page_support",
                    models.BooleanField(
                        default=True, help_text="Split large calendars across pages"
                    ),
                ),
                (
                    "compress_pdf",
                    models.BooleanField(
                        default=False, help_text="Compress PDF (smaller file size)"
                    ),
                ),
                (
                    "header_logo_url",
                    models.URLField(
                        blank=True, help_text="URL to logo image for PDF header"
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(blank=True, help_text="Custom CSS for PDF export"),
                ),
                (
                    "watermark_text",
                    models.CharField(
                        blank=True, help_text="Watermark text", max_length=100
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, help_text="Default author name", max_length=100
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, help_text="Organization name", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "booking_pdfexportsettings",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting identifier", max_length=100, unique=True
                    ),
                ),
                ("value", models.TextField(help_text="Setting value (stored as text)")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "Text String"),
                            ("integer", "Integer"),
                            ("boolean", "True/False"),
                            ("json", "JSON Data"),
                            ("float", "Decimal Number"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What this setting controls"),
                ),
                (
                    "category",
                    models.CharField(
                        default="general", help_text="Setting category", max_length=50
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True, help_text="Can be modified through admin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "booking_systemsetting",
                "ordering": ["category", "key"],
            },
        ),
    ]
