# Generated by Django 5.2.3 on 2025-06-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_add_pdf_export_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="dependency_conditions",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional dependency conditions"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="dependency_type",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential (must complete in order)"),
                    ("parallel", "Parallel (can run concurrently after prerequisites)"),
                    (
                        "conditional",
                        "Conditional (depends on outcome of prerequisites)",
                    ),
                ],
                default="sequential",
                help_text="How this booking depends on prerequisites",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="prerequisite_bookings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bookings that must be completed before this one",
                related_name="dependent_bookings",
                to="booking.booking",
            ),
        ),
    ]
