# Generated by Django 5.2.3 on 2025-06-15 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_add_booking_dependencies_and_waiting_list"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("desired_start_time", models.DateTimeField(help_text="Preferred start time")),
                ("desired_end_time", models.DateTimeField(help_text="Preferred end time")),
                ("title", models.CharField(help_text="Proposed booking title", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Proposed booking description")),
                ("flexible_start", models.BooleanField(default=False, help_text="Can start at different time")),
                ("flexible_duration", models.BooleanField(default=False, help_text="Can use shorter duration")),
                ("min_duration_minutes", models.PositiveIntegerField(default=60, help_text="Minimum acceptable duration in minutes")),
                ("max_wait_days", models.PositiveIntegerField(default=7, help_text="Maximum days willing to wait")),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")], default="normal", max_length=10)),
                ("auto_book", models.BooleanField(default=False, help_text="Automatically book when slot becomes available")),
                ("notification_hours_ahead", models.PositiveIntegerField(default=24, help_text="Hours ahead to notify of availability")),
                ("status", models.CharField(choices=[("waiting", "Waiting"), ("notified", "Notified of Availability"), ("booked", "Successfully Booked"), ("expired", "Expired"), ("cancelled", "Cancelled")], default="waiting", max_length=20)),
                ("position", models.PositiveIntegerField(default=1, help_text="Position in waiting list")),
                ("times_notified", models.PositiveIntegerField(default=0)),
                ("last_notification_sent", models.DateTimeField(blank=True, null=True)),
                ("availability_window_start", models.DateTimeField(blank=True, help_text="When slot became available", null=True)),
                ("availability_window_end", models.DateTimeField(blank=True, help_text="Until when slot is available", null=True)),
                ("response_deadline", models.DateTimeField(blank=True, help_text="Deadline to respond to availability", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, help_text="When this entry expires", null=True)),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="waiting_list_entries", to="booking.resource")),
                ("resulting_booking", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="waiting_list_entry", to="booking.booking")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="waiting_list_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "booking_waitinglistentry",
                "ordering": ["priority", "position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["resource", "status"], name="booking_wai_resourc_2b85e5_idx"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["user", "status"], name="booking_wai_user_id_da6e2c_idx"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["priority", "position"], name="booking_wai_priorit_56abb0_idx"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["desired_start_time"], name="booking_wai_desired_4cd2e3_idx"),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(fields=["expires_at"], name="booking_wai_expires_4c5d7a_idx"),
        ),
    ]