# Generated by Django 5.2.3 on 2025-06-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_create_waiting_list_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="User's preferred timezone",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("DD/MM/YYYY", "DD/MM/YYYY (European)"),
                    ("MM/DD/YYYY", "MM/DD/YYYY (US)"),
                    ("YYYY-MM-DD", "YYYY-MM-DD (ISO)"),
                    ("DD-MM-YYYY", "DD-MM-YYYY"),
                    ("DD.MM.YYYY", "DD.MM.YYYY (German)"),
                ],
                default="DD/MM/YYYY",
                help_text="Preferred date format",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("24h", "24-hour (13:30)"),
                    ("12h", "12-hour (1:30 PM)"),
                ],
                default="24h",
                help_text="Preferred time format",
                max_length=10,
            ),
        ),
    ]