# Generated by Django 5.2.3 on 2025-06-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_approval_workflow_system"),
    ]

    operations = []
