# Generated by Django 5.2.3 on 2025-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_approval_workflow_final"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="approvaldelegation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="approvaldelegation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="approvaldelegation",
            name="delegate",
        ),
        migrations.RemoveField(
            model_name="approvaldelegation",
            name="delegator",
        ),
        migrations.RenameIndex(
            model_name="waitinglistentry",
            new_name="booking_wai_resourc_a500ad_idx",
            old_name="booking_wai_resourc_2b85e5_idx",
        ),
        migrations.RenameIndex(
            model_name="waitinglistentry",
            new_name="booking_wai_user_id_641ea8_idx",
            old_name="booking_wai_user_id_da6e2c_idx",
        ),
        migrations.RenameIndex(
            model_name="waitinglistentry",
            new_name="booking_wai_priorit_14bfd8_idx",
            old_name="booking_wai_priorit_56abb0_idx",
        ),
        migrations.RenameIndex(
            model_name="waitinglistentry",
            new_name="booking_wai_desired_c44fe0_idx",
            old_name="booking_wai_desired_4cd2e3_idx",
        ),
        migrations.RenameIndex(
            model_name="waitinglistentry",
            new_name="booking_wai_expires_814285_idx",
            old_name="booking_wai_expires_4c5d7a_idx",
        ),
        migrations.RemoveField(
            model_name="approvalstatistics",
            name="delegations_given",
        ),
        migrations.RemoveField(
            model_name="approvalstatistics",
            name="delegations_received",
        ),
        migrations.DeleteModel(
            name="ApprovalDelegation",
        ),
    ]
