# Generated by Django 5.2.3 on 2025-06-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_alter_approvaldelegation_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Our Lab", max_length=200)),
                (
                    "content",
                    models.TextField(
                        help_text="Main content for the about page. HTML is allowed."
                    ),
                ),
                ("facility_name", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                (
                    "operating_hours",
                    models.TextField(
                        blank=True, help_text="Describe your normal operating hours"
                    ),
                ),
                (
                    "policies_url",
                    models.URLField(
                        blank=True, help_text="Link to detailed policies document"
                    ),
                ),
                ("emergency_contact", models.CharField(blank=True, max_length=200)),
                (
                    "safety_information",
                    models.TextField(
                        blank=True,
                        help_text="Important safety information for lab users",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one AboutPage can be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Pages",
                "db_table": "booking_aboutpage",
            },
        ),
    ]
