# Generated by Django 5.2.3 on 2025-06-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0026_aboutpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_login",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of user's first login", null=True
            ),
        ),
    ]
