# Generated by Django 5.2.3 on 2025-06-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0028_alter_emailtemplate_notification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(default="fas fa-graduation-cap", max_length=50),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tutorial Category",
                "verbose_name_plural": "Tutorial Categories",
                "db_table": "booking_tutorialcategory",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "target_roles",
                    models.JSONField(
                        default=list, help_text="User roles this tutorial applies to"
                    ),
                ),
                (
                    "target_pages",
                    models.JSONField(
                        default=list,
                        help_text="Pages where this tutorial can be triggered",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Start"),
                            ("first_login", "First Login"),
                            ("role_change", "Role Change"),
                            ("page_visit", "Page Visit"),
                            ("feature_access", "Feature Access"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Tutorial steps configuration"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether users must complete this tutorial",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_start",
                    models.BooleanField(
                        default=False, help_text="Auto-start when conditions are met"
                    ),
                ),
                (
                    "allow_skip",
                    models.BooleanField(
                        default=True, help_text="Allow users to skip this tutorial"
                    ),
                ),
                (
                    "show_progress",
                    models.BooleanField(
                        default=True, help_text="Show progress indicator"
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tutorials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorials",
                        to="booking.tutorialcategory",
                    ),
                ),
            ],
            options={
                "db_table": "booking_tutorial",
                "ordering": ["category__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TutorialAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_starts", models.PositiveIntegerField(default=0)),
                ("total_completions", models.PositiveIntegerField(default=0)),
                ("total_skips", models.PositiveIntegerField(default=0)),
                ("total_abandons", models.PositiveIntegerField(default=0)),
                (
                    "average_completion_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Average completion time in seconds"
                    ),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0.0, help_text="Average user rating"),
                ),
                (
                    "step_completion_rates",
                    models.JSONField(
                        default=dict, help_text="Completion rate for each step"
                    ),
                ),
                (
                    "step_drop_off_points",
                    models.JSONField(
                        default=list, help_text="Steps where users commonly drop off"
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "tutorial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="booking.tutorial",
                    ),
                ),
            ],
            options={
                "db_table": "booking_tutorialanalytics",
            },
        ),
        migrations.CreateModel(
            name="UserTutorialProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list, help_text="List of completed step indices"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent in seconds"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times tutorial was started"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="User rating 1-5", null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True, help_text="User feedback")),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="booking.tutorial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_usertutorialprogress",
                "ordering": ["-last_accessed_at"],
                "unique_together": {("user", "tutorial")},
            },
        ),
    ]
