# Remove tutorial system
# Generated by Django 5.2.3 on 2025-06-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0030_maintenancevendor_maintenance_actual_cost_and_more"),
    ]

    operations = [
        # Drop tutorial-related tables in reverse dependency order (SQLite doesn't support CASCADE)
        migrations.RunSQL("DROP TABLE IF EXISTS booking_tutorialanalytics;"),
        migrations.RunSQL("DROP TABLE IF EXISTS booking_usertutorialprogress;"),
        migrations.RunSQL("DROP TABLE IF EXISTS booking_tutorial;"),
        migrations.RunSQL("DROP TABLE IF EXISTS booking_tutorialcategory;"),
    ]
